### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by ammarahm-ed** [ammarahm-ed/react-native-mmkv-storage#1]

**Comment by ammarahm-ed** [comment]
The great thing about MMKV is that its very simple and easy to use. Also it is very fast, so I am thinking of maintaining this library here in long term which means if you are using it you dont have to worry because I will be fixing things on the way. So here is the list of things that need to be implemented if someone is interested in contributing.

[dev branch to track development for next release](https://github.com/ammarahm-ed/react-native-mmkv-storage/tree/dev)

- [x]  Support to set int and boolean data types.
- [x]  Encryption 
- [x]  Create unlimited instances of database, for example, an encrypted instance with everything important and a normal one such as app settings or something that you are storing. 
- [x]  Data type Indexer 
- [x]  Rewrite docs using docsify.
- [x]  Add some optimizations to give further performance boost
